version: 0.2

env:
  variables:
    IMAGE_BASE_NAME: "service-name"
    REGISTRY: "504480069810.dkr.ecr.us-east-1.amazonaws.com/flask-app-ecr-repo"
    SHELL: /bin/bash
    TC_DYNAMO_TABLE: "Candidates"
    AWS_DEFAULT_REGION: us-east-1
    USER: "aws_code_build"
    PIPENV_NOSPIN: 1

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - aws --version
      - echo "Login to AWS ECR docker registry"
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REGISTRY}
  pre_build:
    commands:
      - echo Loggin in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login ---region $AWS_DEFAULT_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID |awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on $(date)
      - export DOCKER_IMG_TAG=${REGISTRY}/${IMAGE_BASE_NAME}:${GITHUB_TAG}
      - export DOCKER_IMG_TAG_LATEST=${REGISTRY}/${IMAGE_BASE_NAME}:${GITHUB_BRANCH}.latest
      - |-
        if [ "${GITHUB_TAG}" = "" ] ; then
          export DOCKER_IMG_TAG=${REGISTRY}/${IMAGE_BASE_NAME}:${GITHUB_BRANCH}.${GITHUB_COMMIT}
          export GITHUB_TAG=${GITHUB_COMMIT}
        fi
      - echo "Building docker image with tags ${DOCKER_IMG_TAG} and ${DOCKER_IMG_TAG_LATEST}"
      - >
        docker build
        --build-arg GIT_HASH="${GITHUB_COMMIT}"
        --build-arg GIT_BRANCH="${GITHUB_BRANCH}"
        --build-arg VERSION="${GITHUB_TAG}"
        --build-arg AUTHOR="CI"
        -t ${DOCKER_IMG_TAG} -t ${DOCKER_IMG_TAG_LATEST} .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REGISTRY:latest
      - docker push $REGISTRY:$IMAGE_TAG
